### PR TITLE
Adds support for sending email via flask-mail in the App Engine environment

### PR DESCRIPTION
**Pull request by bslatkin**
Travis build is working. This helps with #21. Tested in App Engine production and works as expected for my use-cases.

### CODE REVIEW

**Comment by bslatkin** [comment]
Rebased. All green. Added an example app. Also added a requirements.txt file to make it easy to develop on this with virtualenv. Can we land this soon?

**Comment by bslatkin** [comment]
Hey @jamesonjlee sorry I'm a pest but I'd love to get this merged so I can use "pip install flask-mail" for deployments to App Engine :) Let me know what I can do!

**Comment by bslatkin** [comment]
@mattupstate Do you have any interest in pulling this one?

**Comment by russomi** [comment]
+1 to have this one included.

**Comment by mattupstate** [comment]
@bslatkin As I mentioned in #27 that I'd like to utilize some sort of pattern (adapter, provider, etc) so that writing support for additional email backends would be well defined. As it stands the code you submitted does not afford this.

**Comment by bslatkin** [comment]
@mattupstate You mean #21? It looks like my contribution here is the first additional backend the codebase has seen? Maybe once there's a second backend to incorporate that's the time to address #21 head on? If you look at my diff it's quite minimal. MIME Messages are the common API.

Given you have a better idea of how the code fits together, it would make sense to me that you'd factor out the adapter/pluggable interface you're describing, and then I could implement against it. I'm not up for doing that myself because I anticipate I'll do it wrong since you have some idea in your mind of what it should look like.

Otherwise, #21 has been sitting there for almost 3 years so this does not bode well. I'll abandon this patch until #21 is addressed by someone else.

**Pull request closed without merging**
